config/routes.rb
Postit::Application.routes.draw do
  
  root to: 'posts#index'

  get 'login', to: "sessions#new"
  get 'logout', to: "sessions#destroy"
  post 'login', to: "sessions#create"
  get 'register', to: "users#new", as: "register"

  resources :users, only: [:show, :new, :edit, :create, :update]
  resources :posts do
      resources :comments
      resource :votes, only: [:create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :post_id, :user_id

  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :url, :user_id
  validates_presence_of :title, :url, :user_id

  belongs_to :user
  has_many :comments
  has_many :votes

  def total_votes
      self.votes.where(votes: true).size - self.votes.where(votes: false).size
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :name, :email, :password
  validates_presence_of :name, :email, :password
  
  has_many :posts
  has_many :comments
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :post_id, :votes

  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def require_login
  	if !logged_in?
  		redirect_to root_path, notice: "You must be logged in!"
  	end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login, only: [:create]

  def index
    @post = Post.find(params[:post_id]) # allows you to use post_id, go into db, look up post, and set it as instance variable, then can iterate through its comments
  end


  def create
    @post = Post.find(params[:post_id]) # gets the post that was created
    @comment = Comment.new(params[:comment]) # params comment is going to return the inner hash, the method Comment.create expects the hash
    @comment.user_id = current_user.id
    @comment.post_id = @post.id

    respond_to do |format|
      if @comment.save
        format.html {redirect_to post_comments_path(@post), notice: "Comment created!"}

      else
        format.html {redirect_to post_comments_path(@post), notice: "Comment not created!"}
      end
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_login, except: [:index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to root_path, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		if login(params[:name], params[:password])
			redirect_to root_url, notice: 'Logged in!'
		else
			render 'new'
		end
	end

	def destroy
		logout
		redirect_to root_url, notice: 'Logged out'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, except: [:new, :create, :show]

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_filter :require_login

	def create
		@post = Post.find(params[:post_id])
		if params[:direction] == 'up'
			@post.votes.create(votes: true)
			msg = "Upvoted #{@post.title}"
		else
			@post.votes.create(votes: false)
			msg = "Downvoted #{@post.title}"
		end

		respond_to do |format|
			format.html { redirect_to posts_path, notice: msg }
			format.js
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def fix_url(url)
		url.starts_with?('http://') ? url : 'http://' + url
	end

	def display_name(user)
		user ? user.name : ""
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit 'submit', :class => 'btn' %>
  </div>
<% end %>

app/views/comments/index.html.erb
This post has <%= @post.comments.size %> comments.

<p>
	<% @post.comments.each do |comment| %>
		<%= comment.body %>
		by <%= comment.user.name %>
		<hr />
	<% end %>
</p>

<% if logged_in? %>
Add a comment:
<p>
	<%= form_for(Comment.new, url: post_comments_path(@post)) do |f| %>
		<%= f.text_area :body %>
		<br />
		<%= f.submit "Add a Comment" , :class => 'btn' %>
	<% end %>
</p>
<% end %>

app/views/comments/show.html.erb
<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Postit" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Postit</a>
          <div class="container nav-collapse">
            <p class="navbar-text pull-right">
               <% if logged_in? %>
              <%= "Logged in as #{link_to current_user.name, user_path(current_user.id)}".html_safe %>
              (<%= link_to 'logout', logout_path, :class => 'navbar-link' %>)
            <% else %>
              <%= link_to "Log in", login_path, :class => 'navbar-link' %> 
              |
              <%= link_to "Register", register_path, :class => 'navbar-link' %>
            <% end %>
            </p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
            <br/>

           	<p id="notice"><%= notice %></p>
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Menu</h3>
                <ul class="nav nav-list">
                  <li class="nav-header"></li>
                  <li><%= link_to 'New Post', new_post_path, :class => 'btn' if logged_in? %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Dexter Zhuang 2012</p>
      </footer>
      <% if Rails.env.development? %>
      	<%= "DEBUG: #{controller.controller_name}::#{controller.action_name}" %>
      <% end %>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', root_path %>

app/views/posts/index.html.erb
<p class="lead"> Post, vote, and comment on your favorite websites across the web.</p>

<table class="table table-striped table-hover">
  <thead id="heading">
    <tr>
        <th></th>
        <th>Votes</th>
        <th>Title</th>
        <th>Submitted by</th>
        <th>Comments</th>
    </tr>
  </thead>


  <tbody>
        <% counter = 1 %>
    <% @posts.each do |post| %>
    <tr>
        <td id="count"> <%= "#{counter}." %></td>
        <td> 
            <%= link_to post_votes_path(post, direction: 'up'), method: 'post', remote: true  do %> 
            <i class="icon-arrow-up"></i>
            <% end %>
            <br/> 
            <span id="total_votes_<%=post.id%>">
            <%= "(#{post.total_votes})" %>
            </span>
            <br/>
            <%= link_to post_votes_path(post, direction: 'down'), method: 'post', remote: true do %>
            <i class="icon-arrow-down"></i>
            <% end %> 
            </td>
        <td> <%= link_to(post.title, fix_url(post.url)) %>
            <br/>
            <%= link_to(post.url, fix_url(post.url)) %>
        </td>
        <td><%=  "submitted by #{display_name(post.user)}" %> </td>
        <td id="comments"> <%= link_to "#{post.comments.size} comments", post_comments_path(post) %> </td>
    </tr>
    <% counter += 1 %>
    <% end %>
  </tbody>
</table>

<br />

app/views/posts/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/posts/show.html.erb
<p>
  <b>Title</b>
  <%= @post.title %>
</p>
<p>
  <b>Url:</b>
  <%= @post.url %>
</p>
<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', root_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %> 
  </div>
  <div class="actions">
    <%= f.submit 'submit', :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1> Profile page for <%= @user.name %></h1>
<br>
<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |

<h3><%= "#{@user.name}'s posts" %></h3>
<hr />
<table class="table table-striped table-hover">
  <thead id="heading">
    <tr>
        <th></th>
        <th>Votes</th>
        <th>Title</th>
        <th>Posted</th>
        <th>Comments</th>
    </tr>
  </thead>


  <tbody>
        <% counter = 1 %>
    <% @user.posts.each do |post| %>
    <tr>
        <td id="count"> <%= "#{counter}." %></td>
        <td> 
            <%= link_to post_votes_path(post, direction: 'up'), method: 'post', remote: true  do %> 
            <i class="icon-arrow-up"></i>
            <% end %>
            <br/> 
            <span id="total_votes_<%=post.id%>">
            <%= "(#{post.total_votes})" %>
            </span>
            <br/>
            <%= link_to post_votes_path(post, direction: 'down'), method: 'post', remote: true do %>
            <i class="icon-arrow-down"></i>
            <% end %> 
            </td>
        <td> <%= link_to(post.title, fix_url(post.url)) %>
            <br/>
            <%= link_to(post.url, fix_url(post.url)) %>
        </td>
        <td><%=  post.created_at.utc.strftime("%r on %D") %> </td>
        <td id="comments"> <%= link_to "#{post.comments.size} comments", post_comments_path(post) %> </td>
    </tr>
    <% counter += 1 %>
    <% end %>
  </tbody>
</table>


<h3><%= "#{@user.name}'s comments" %></h3>
<hr />

<p>
	<% @user.comments.each do |comment| %>
		"<%= comment.body %>"
		commented on <%= comment.post.title %>
		<hr />
	<% end %>
</p>

app/views/votes/create.js.erb
$("#total_votes_<%=@post.id%>").html("(<%=@post.total_votes%>)")